// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package go_hubspot

import (
	"sync"
)

// Ensure, that IHubspotFormAPIMock does implement IHubspotFormAPI.
// If this is not the case, regenerate this file with moq.
var _ IHubspotFormAPI = &IHubspotFormAPIMock{}

// IHubspotFormAPIMock is a mock implementation of IHubspotFormAPI.
//
// 	func TestSomethingThatUsesIHubspotFormAPI(t *testing.T) {
//
// 		// make and configure a mocked IHubspotFormAPI
// 		mockedIHubspotFormAPI := &IHubspotFormAPIMock{
// 			GetPageURLFunc: func(after string) string {
// 				panic("mock out the GetPageURL method")
// 			},
// 			QueryFunc: func(after string) (*HubspotResponse, error) {
// 				panic("mock out the Query method")
// 			},
// 			SearchForKeyValueFunc: func(key string, value string) (map[string]string, error) {
// 				panic("mock out the SearchForKeyValue method")
// 			},
// 		}
//
// 		// use mockedIHubspotFormAPI in code that requires IHubspotFormAPI
// 		// and then make assertions.
//
// 	}
type IHubspotFormAPIMock struct {
	// GetPageURLFunc mocks the GetPageURL method.
	GetPageURLFunc func(after string) string

	// QueryFunc mocks the Query method.
	QueryFunc func(after string) (*HubspotResponse, error)

	// SearchForKeyValueFunc mocks the SearchForKeyValue method.
	SearchForKeyValueFunc func(key string, value string) (map[string]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetPageURL holds details about calls to the GetPageURL method.
		GetPageURL []struct {
			// After is the after argument value.
			After string
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// After is the after argument value.
			After string
		}
		// SearchForKeyValue holds details about calls to the SearchForKeyValue method.
		SearchForKeyValue []struct {
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value string
		}
	}
	lockGetPageURL        sync.RWMutex
	lockQuery             sync.RWMutex
	lockSearchForKeyValue sync.RWMutex
}

// GetPageURL calls GetPageURLFunc.
func (mock *IHubspotFormAPIMock) GetPageURL(after string) string {
	if mock.GetPageURLFunc == nil {
		panic("IHubspotFormAPIMock.GetPageURLFunc: method is nil but IHubspotFormAPI.GetPageURL was just called")
	}
	callInfo := struct {
		After string
	}{
		After: after,
	}
	mock.lockGetPageURL.Lock()
	mock.calls.GetPageURL = append(mock.calls.GetPageURL, callInfo)
	mock.lockGetPageURL.Unlock()
	return mock.GetPageURLFunc(after)
}

// GetPageURLCalls gets all the calls that were made to GetPageURL.
// Check the length with:
//     len(mockedIHubspotFormAPI.GetPageURLCalls())
func (mock *IHubspotFormAPIMock) GetPageURLCalls() []struct {
	After string
} {
	var calls []struct {
		After string
	}
	mock.lockGetPageURL.RLock()
	calls = mock.calls.GetPageURL
	mock.lockGetPageURL.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *IHubspotFormAPIMock) Query(after string) (*HubspotResponse, error) {
	if mock.QueryFunc == nil {
		panic("IHubspotFormAPIMock.QueryFunc: method is nil but IHubspotFormAPI.Query was just called")
	}
	callInfo := struct {
		After string
	}{
		After: after,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(after)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//     len(mockedIHubspotFormAPI.QueryCalls())
func (mock *IHubspotFormAPIMock) QueryCalls() []struct {
	After string
} {
	var calls []struct {
		After string
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// SearchForKeyValue calls SearchForKeyValueFunc.
func (mock *IHubspotFormAPIMock) SearchForKeyValue(key string, value string) (map[string]string, error) {
	if mock.SearchForKeyValueFunc == nil {
		panic("IHubspotFormAPIMock.SearchForKeyValueFunc: method is nil but IHubspotFormAPI.SearchForKeyValue was just called")
	}
	callInfo := struct {
		Key   string
		Value string
	}{
		Key:   key,
		Value: value,
	}
	mock.lockSearchForKeyValue.Lock()
	mock.calls.SearchForKeyValue = append(mock.calls.SearchForKeyValue, callInfo)
	mock.lockSearchForKeyValue.Unlock()
	return mock.SearchForKeyValueFunc(key, value)
}

// SearchForKeyValueCalls gets all the calls that were made to SearchForKeyValue.
// Check the length with:
//     len(mockedIHubspotFormAPI.SearchForKeyValueCalls())
func (mock *IHubspotFormAPIMock) SearchForKeyValueCalls() []struct {
	Key   string
	Value string
} {
	var calls []struct {
		Key   string
		Value string
	}
	mock.lockSearchForKeyValue.RLock()
	calls = mock.calls.SearchForKeyValue
	mock.lockSearchForKeyValue.RUnlock()
	return calls
}
