// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ehe_hubspot

import (
	"sync"
)

// Ensure, that IHubspotFormAPIMock does implement IHubspotFormAPI.
// If this is not the case, regenerate this file with moq.
var _ IHubspotFormAPI = &IHubspotFormAPIMock{}

// IHubspotFormAPIMock is a mock implementation of IHubspotFormAPI.
//
// 	func TestSomethingThatUsesIHubspotFormAPI(t *testing.T) {
//
// 		// make and configure a mocked IHubspotFormAPI
// 		mockedIHubspotFormAPI := &IHubspotFormAPIMock{
// 			GetPageURLFunc: func(after string) string {
// 				panic("mock out the GetPageURL method")
// 			},
// 			QueryFunc: func(after string) (*HubspotResponse, error) {
// 				panic("mock out the Query method")
// 			},
// 			SearchForApplicationIDFunc: func(applicationId string) (map[string]string, error) {
// 				panic("mock out the SearchForApplicationID method")
// 			},
// 		}
//
// 		// use mockedIHubspotFormAPI in code that requires IHubspotFormAPI
// 		// and then make assertions.
//
// 	}
type IHubspotFormAPIMock struct {
	// GetPageURLFunc mocks the GetPageURL method.
	GetPageURLFunc func(after string) string

	// QueryFunc mocks the Query method.
	QueryFunc func(after string) (*HubspotResponse, error)

	// SearchForApplicationIDFunc mocks the SearchForApplicationID method.
	SearchForApplicationIDFunc func(applicationId string) (map[string]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetPageURL holds details about calls to the GetPageURL method.
		GetPageURL []struct {
			// After is the after argument value.
			After string
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// After is the after argument value.
			After string
		}
		// SearchForApplicationID holds details about calls to the SearchForApplicationID method.
		SearchForApplicationID []struct {
			// ApplicationId is the applicationId argument value.
			ApplicationId string
		}
	}
	lockGetPageURL             sync.RWMutex
	lockQuery                  sync.RWMutex
	lockSearchForApplicationID sync.RWMutex
}

// GetPageURL calls GetPageURLFunc.
func (mock *IHubspotFormAPIMock) GetPageURL(after string) string {
	if mock.GetPageURLFunc == nil {
		panic("IHubspotFormAPIMock.GetPageURLFunc: method is nil but IHubspotFormAPI.GetPageURL was just called")
	}
	callInfo := struct {
		After string
	}{
		After: after,
	}
	mock.lockGetPageURL.Lock()
	mock.calls.GetPageURL = append(mock.calls.GetPageURL, callInfo)
	mock.lockGetPageURL.Unlock()
	return mock.GetPageURLFunc(after)
}

// GetPageURLCalls gets all the calls that were made to GetPageURL.
// Check the length with:
//     len(mockedIHubspotFormAPI.GetPageURLCalls())
func (mock *IHubspotFormAPIMock) GetPageURLCalls() []struct {
	After string
} {
	var calls []struct {
		After string
	}
	mock.lockGetPageURL.RLock()
	calls = mock.calls.GetPageURL
	mock.lockGetPageURL.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *IHubspotFormAPIMock) Query(after string) (*HubspotResponse, error) {
	if mock.QueryFunc == nil {
		panic("IHubspotFormAPIMock.QueryFunc: method is nil but IHubspotFormAPI.Query was just called")
	}
	callInfo := struct {
		After string
	}{
		After: after,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(after)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//     len(mockedIHubspotFormAPI.QueryCalls())
func (mock *IHubspotFormAPIMock) QueryCalls() []struct {
	After string
} {
	var calls []struct {
		After string
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// SearchForApplicationID calls SearchForApplicationIDFunc.
func (mock *IHubspotFormAPIMock) SearchForApplicationID(applicationId string) (map[string]string, error) {
	if mock.SearchForApplicationIDFunc == nil {
		panic("IHubspotFormAPIMock.SearchForApplicationIDFunc: method is nil but IHubspotFormAPI.SearchForApplicationID was just called")
	}
	callInfo := struct {
		ApplicationId string
	}{
		ApplicationId: applicationId,
	}
	mock.lockSearchForApplicationID.Lock()
	mock.calls.SearchForApplicationID = append(mock.calls.SearchForApplicationID, callInfo)
	mock.lockSearchForApplicationID.Unlock()
	return mock.SearchForApplicationIDFunc(applicationId)
}

// SearchForApplicationIDCalls gets all the calls that were made to SearchForApplicationID.
// Check the length with:
//     len(mockedIHubspotFormAPI.SearchForApplicationIDCalls())
func (mock *IHubspotFormAPIMock) SearchForApplicationIDCalls() []struct {
	ApplicationId string
} {
	var calls []struct {
		ApplicationId string
	}
	mock.lockSearchForApplicationID.RLock()
	calls = mock.calls.SearchForApplicationID
	mock.lockSearchForApplicationID.RUnlock()
	return calls
}
